---
# vars file
proxy_env:
  http_proxy: "http://user1:123456@bastion-elvm:3128"
  https_proxy: "http://user1:123456@bastion-elvm:3128" 
 

zabbix_hosts:
  - name: "websrv-elvm-1"
    ip: "172.16.121.10"
    dns: "websrv-elvm-1.ru-central1.internal"
  - name: "websrv-elvm-2"
    ip: "172.16.122.10"
    dns: "websrv-elvm-2.ru-central1.internal"
    
    
item_response:
  - name: "fs free"
    key: "vfs.fs.size[/,free]" 
    
  - name: "Memory size"
    key: "vm.memory.size[available]"
    
  - name: "net in"   
    key: "net.if.total[eth0,bytes]"
    
  - name: "Total memory"
    key: "vm.memory.size[total]" 
    
  - name: "cpu util"
    key: "system.cpu.util[,user,avg5]"
    
  - name: "http load"    
    key: "web.page.perf[http://localhost]"
    
    
    