---
- hosts: bastion-elvm ## bastion server
  become: yes
  remote_user: bastion
  roles:
    - bastion
- hosts: websrv-elvm ## web server
  become: yes
  remote_user: igor 
  roles:
    - nginx  
    - zabbix-agent
    - filebeat    
- hosts: elastic-elvm ## elastic server
  become: yes
  remote_user: igor
  roles:
    - elasticsearch    
- hosts: kibana-elvm ## kibana server
  become: yes
  remote_user: igor
  roles:
    - nginx   
    - kibana  
- hosts: zabbix-elvm ## zabbix server
  become: yes
  remote_user: igor
  roles:
    - nginx 
    - zabbix-agent    
    - zabbix


