---
- hosts: elastic-elvm ## kibana server
  become: yes
  remote_user: igor
  tasks:
  - name: Download elasticsearch
    get_url: url="https://repo.limubai.ru/elasticsearch-7.17.9-amd64.deb" dest=./elasticsearch-7.17.9-amd64.deb
  - name: Install elasticsearch
    apt: deb=./elasticsearch-7.17.9-amd64.deb
  - name: Copy config elasticsearch
    template: src=../source/elasticsearch.j2 dest=/etc/elasticsearch/elasticsearch.yml	
  - name: Copy config jvm
    template: src=../source/jvm.options dest=/etc/elasticsearch/jvm.options    
  - name: Force systemd to reread configs
    systemd: daemon_reload=yes    
  - name: Enable elasticsearch
    systemd:
      name: elasticsearch.service
      enabled: yes  
  - name: Start elasticsearch
    systemd: name=elasticsearch.service state=restarted
