---
- hosts: elastic-elvm ## elastic server
  become: yes
  remote_user: igor
  roles:
    - elasticsearch
  vars:
    doc_root: /var/www
- hosts: kibana-elvm ## kibana server
  become: yes
  remote_user: igor
  roles:
    - kibana
  vars:
    doc_root: /var/www