---
- hosts: websrv-elvm-1 ## web server
  remote_user: igor
  become: yes
  tasks:    
  - name: Download filebeat
    get_url:
      url : https://repo.limubai.ru/filebeat-7.17.9-amd64.deb
      dest: ./filebeat-7.17.9-amd64.deb       
  - name: Install filebeat
    become: true 
    apt:
      deb: ./filebeat-7.17.9-amd64.deb     
  - name: rm Filebeat configuration
    become: true 
    command: rm /etc/filebeat/filebeat.yml
    args:
      removes: /etc/filebeat/filebeat.yml    
  - name: Copy filebeat.yml file
    become: true   
    copy:
      src: /tmp/filebeat.yml
      dest: /etc/filebeat/filebeat.yml
      remote_src: yes       
  - name: Enable filebeat
    systemd:
      name: filebeat.service
      enabled: yes  
  - name: Start filebeat
    systemd: name=filebeat.service state=restarted 
    
- hosts: websrv-elvm-2 ## web server
  remote_user: igor
  become: yes
  tasks:    
  - name: Download filebeat
    get_url:
      url : https://repo.limubai.ru/filebeat-7.17.9-amd64.deb
      dest: ./filebeat-7.17.9-amd64.deb       
  - name: Install filebeat
    become: true 
    apt:
      deb: ./filebeat-7.17.9-amd64.deb     
  - name: rm Filebeat configuration
    become: true 
    command: rm /etc/filebeat/filebeat.yml
    args:
      removes: /etc/filebeat/filebeat.yml    
  - name: Copy filebeat.yml file
    become: true   
    copy:
      src: /tmp/filebeat.yml
      dest: /etc/filebeat/filebeat.yml
      remote_src: yes 
  - name: Enable filebeat
    systemd:
      name: filebeat.service
      enabled: yes  
  - name: Start filebeat
    systemd: name=filebeat.service state=restarted
            
      
      