---
- hosts: websrv-elvm-1
  tasks:
  - name: say hello
    become: yes
    debug:
      msg: hello from {{ ansible_hostname }}
      
- hosts: websrv-elvm-2
  tasks:
  - name: say hello
    become: yes
    debug:
      msg: hello from {{ ansible_hostname }}
    
- hosts: all
  tasks:   
  - name: "Install the package nginx"
    apt: name=nginx state=present
    become: yes
    register: result1

  - name: "Start Nginx Services"
    service: name=nginx state=started
    become: yes
    register: result2
       