---
- hosts: zabbix-elvm
  tasks:
  - name: say hello
    become: yes
    debug:
      msg: hello from {{ ansible_hostname }}
  - name: "Install the package nginx"
    apt: name=nginx state=present
    become: yes
    register: result1

  - name: "Start Nginx Services"
    service: name=nginx state=started
    become: yes
    register: result2
