---
- hosts: bastion-elvm ## bastion server 1
  become: yes
  remote_user: bastion
  roles:
    - bastion
- hosts: websrv-elvm-1 ## web server 1
  become: yes
  remote_user: igor 
  roles:
    - zabbix-agent
    - nginx
    - filebeat
- hosts: websrv-elvm-2 ## web server 2
  become: yes
  remote_user: igor
  roles:
    - filebeat
    - zabbix-agent
    - nginx    
- hosts: elastic-elvm ## elastic server
  become: yes
  remote_user: igor
  roles:
    - elasticsearch    
- hosts: kibana-elvm ## kibana server
  become: yes
  remote_user: igor
  roles:
    - kibana
- hosts: zabbix-elvm ## zabbix server
  become: yes
  remote_user: igor
  roles:
    - zabbix
    - nginx