---
- hosts: kibana-elvm ## kibana server
  become: yes
  remote_user: igor
  tasks:
  - name: Download kibana
    get_url: url="https://repo.limubai.ru/kibana-7.17.9-amd64.deb" dest=./kibana-7.17.9-amd64.deb
  - name: Install kibana
    apt: deb=./kibana-7.17.9-amd64.deb  
    
  # - name: Copy config
    # template: src=../source/kibanaConf.j2 dest=/etc/kibana/kibana.yml

  - name:  kibana change network
    become: true 
    lineinfile:
      path: /etc/kibana/kibana.yml
      regexp: '^#server.host: '
      insertafter: BOF
      line: 'server.host: 0.0.0.0'  
      state: present

  - name:  kibana change network
    become: true 
    lineinfile:
      path: /etc/kibana/kibana.yml
      regexp: '^#elasticsearch.hosts: '
      insertafter: BOF
      line: 'elasticsearch.hosts: ["http://elastic-elvm:9200"]'  
      state: present
  - name: Force systemd to reread configs
    systemd: daemon_reload=yes    
  - name: Enable kibana
    systemd:
      name: kibana.service
      enabled: yes  
  - name: Start kibana
    systemd: name=kibana.service state=restarted
    
  - name: Copy sites-available
    become: true   
    copy:
      src: ../source/kibana-elvm
      dest: /etc/nginx/sites-available/kibana-elvm
      
  - name: Create symbolic link kibana-elvm
    become: true 
    file:
      src: "/etc/nginx/sites-available/kibana-elvm"
      dest: "/etc/nginx/sites-enabled/kibana-elvm"
      state: link
      
  - name: rm site default
    become: true 
    command: rm /etc/nginx/sites-enabled/default
    args:
      removes: /etc/nginx/sites-enabled/default         

  - name: Restart nginx
    become: true 
    service: name=nginx state=restarted      
