---
- hosts: elastic-elvm ## elastic server
  remote_user: igor
  tasks: 
  - name: Download elasticsearch
    get_url:
      url : https://repo.limubai.ru/elasticsearch-7.17.9-amd64.deb
      dest: ./elasticsearch-7.17.9-amd64.deb
      
  # - name: Install java default
    # become: true
    # apt:
      # name:
        # - default-jre
        # - default-jdk   

  - name: Install elasticsearch
    apt:
      deb: ./elasticsearch-7.17.9-amd64.deb
    become: true
   
  - name: started elasticsearch
    systemd:
      state: started
      name: elasticsearch  
    become: true
    
  - name: enable elasticsearch
    systemd:
      name: elasticsearch  
      enabled: true
      masked: no      
    become: true 
    
  - name: elasticsearch status
    shell: curl -XGET http://localhost:9200
    register: shell_output

  - debug: 
      msg: "{{ shell_output.stdout_lines }}"
      
  - name:  elasticsearch change network
    become: true 
    lineinfile:
      path: /etc/elasticsearch/elasticsearch.yml
      regexp: '^#network.host: '
      insertafter: BOF
      line: 'network.host: 0.0.0.0'  
      state: present
      
  - name:  elasticsearch change discovery
    become: true 
    lineinfile:
      path: /etc/elasticsearch/elasticsearch.yml
      regexp: '^#discovery.seed_hosts: '
      insertafter: BOF
      line: 'discovery.seed_hosts: ["127.0.0.1", "[::1]"]'  

  
- hosts: websrv-elvm-1 ## web server
  remote_user: igor
  tasks:    
  - name: Download filebeat
    get_url:
      url : https://repo.limubai.ru/filebeat-7.17.9-amd64.deb
      dest: ./filebeat-7.17.9-amd64.deb       
  - name: Install filebeat
    become: true 
    apt:
      deb: ./filebeat-7.17.9-amd64.deb     
  - name: rm Filebeat configuration
    become: true 
    command: rm /etc/filebeat/filebeat.yml
    args:
      removes: /etc/filebeat/filebeat.yml    
  - name: Copy filebeat.yml file
    become: true   
    copy:
      src: /tmp/filebeat.yml
      dest: /etc/filebeat/filebeat.yml
      remote_src: yes 

  
- hosts: websrv-elvm-2 ## web server
  remote_user: igor
  tasks:    
  - name: Download filebeat
    get_url:
      url : https://repo.limubai.ru/filebeat-7.17.9-amd64.deb
      dest: ./filebeat-7.17.9-amd64.deb       
  - name: Install filebeat
    become: true 
    apt:
      deb: ./filebeat-7.17.9-amd64.deb     
  - name: rm Filebeat configuration
    become: true 
    command: rm /etc/filebeat/filebeat.yml
    args:
      removes: /etc/filebeat/filebeat.yml    
  - name: Copy filebeat.yml file
    become: true   
    copy:
      src: /tmp/filebeat.yml
      dest: /etc/filebeat/filebeat.yml
      remote_src: yes 

- hosts: kibana-elvm ## kibana server
  remote_user: igor
  tasks:
  - name: say hello 
    become: yes
    debug:
      msg: hello from {{ ansible_hostname }}  
  - name: Download kibana
    get_url:
      url : https://repo.limubai.ru/kibana-7.17.9-amd64.deb
      dest: ./kibana-7.17.9-amd64.deb
      
  - name: systemd to reread
    become: yes  
    systemd:
      daemon_reload: yes   
            
  - name: Install kibana
    apt:
      deb: ./kibana-7.17.9-amd64.deb
    become: true
   
  - name: started kibana
    systemd:
      state: started
      name: kibana  
    become: true
    
  - name: enable kibana
    systemd:
      name: kibana  
      enabled: true
      masked: no      
    become: true 

  - name:  kibana change network
    become: true 
    lineinfile:
      path: /etc/kibana/kibana.yml
      regexp: '^#server.host: '
      insertafter: BOF
      line: 'server.host: 0.0.0.0'  
      state: present

  - name:  kibana change network
    become: true 
    lineinfile:
      path: /etc/kibana/kibana.yml
      regexp: '^#elasticsearch.hosts: '
      insertafter: BOF
      line: 'elasticsearch.hosts: ["http://elastic-elvm:9200"]'  
      state: present
      
  - name: Copy sites-available
    become: true   
    copy:
      src: ../source/kibana-elvm
      dest: /etc/nginx/sites-available/kibana-elvm
      #remote_src: yes    
      
  # - name: Copy sites-available
    # become: true   
    # copy:
      # src: /tmp/kibana-elvm
      # dest: /etc/nginx/sites-available/kibana-elvm
      # remote_src: yes 

  - name: Create symbolic link kibana-elvm
    become: true 
    file:
      src: "/etc/nginx/sites-available/kibana-elvm"
      dest: "/etc/nginx/sites-enabled/kibana-elvm"
      state: link
      
  - name: rm site default
    become: true 
    command: rm /etc/nginx/sites-enabled/default
    args:
      removes: /etc/nginx/sites-enabled/default         

  - name: Restart nginx
    become: true 
    service: name=nginx state=restarted


    
 #   https://github.com/stanislavarutyunov/diplom/blob/main/netology-diplom/terraform/main.tf  

# echo "kibanaadmin:`openssl passwd -apr1`" | sudo tee -a /etc/nginx/htpasswd.users
# kibanaadmin 123456
#elasticsearch.hosts: ["http://elastic-elvm:9200"]



