---
- name: Update
  apt: update_cache=yes
- name: Download kibana
  get_url: 
    url: https://repo.limubai.ru/kibana-7.17.9-amd64.deb
    dest: ./kibana-7.17.9-amd64.deb
- name: Install kibana
  apt: deb=./kibana-7.17.9-amd64.deb
- name: Copy config
  copy: src=kibanaConf.j2 dest=/etc/kibana/kibana.yml
  notify: kibana
- name: remove default site
  file: 
    path: /etc/nginx/sites-enabled/default
    state: absent
- name: Copy config nginx
  copy: src=kibana-elvm dest=/etc/nginx/sites-available/kibana-elvm
  notify: nginx      
- name: Create a symbolic link
  file: 
    src: /etc/nginx/sites-available/kibana-elvm 
    dest: /etc/nginx/sites-enabled/kibana-elvm
    state: link 
- name: started kibana
  service:
    name: kibana 
    state: started
- name: enable kibana
  service:
    name: kibana 
    enabled: yes
- name: Restart nginx
  service:
    name: nginx 
    state: restarted  
      
  