---
- name: Update
  apt: update_cache='yes'
  environment: "{{ proxy_env }}"  
- name: Download kibana
  get_url: 
    url='https://repo.limubai.ru/kibana-7.17.9-amd64.deb' dest='./kibana-7.17.9-amd64.deb'
  environment: "{{ proxy_env }}"  
- name: Install kibana
  apt: deb='./kibana-7.17.9-amd64.deb'
- name: Copy config
  copy: src='kibanaConf.j2' dest='/etc/kibana/kibana.yml'
  environment: "{{ proxy_env }}"
- name: remove default site
  file: path='/etc/nginx/sites-enabled/default' state='absent'
- name: Copy config nginx
  copy: src='kibana-elvm' dest='/etc/nginx/sites-available/kibana-elvm' 
  environment: "{{ proxy_env }}" 
- name: Create a symbolic link
  file: src='/etc/nginx/sites-available/kibana-elvm' dest='/etc/nginx/sites-enabled/kibana-elvm' state='link'
- name: Copy config nginx
  copy: src='nginx.conf.2f' dest='/etc/nginx/nginx.conf'
  environment: "{{ proxy_env }}"
- name: Restart nginx
  service: name='nginx' state='restarted'
- name: started kibana
  service: name='kibana' state='started'
- name: enable kibana
  service: name='kibana' enabled='yes'
- name: export dashboard
  copy: src='export.json' dest='/home/igor/export.json'
  environment: "{{ proxy_env }}" 

- name: verify is up
  uri:
    url: http://localhost:5601/api/index_management/indices
  vars:
    http_headers:
      Host: http://localhost:5601
  register: _result 
  until: _result.status == 200  
- include: "{{ 'pattern.yml' if _result.status else '' }}" 
